#!/usr/bin/env python3
from pathlib import Path
import re, json

root = Path.cwd()
skip = {".git","node_modules",".venv","venv"}
generated_dirs = {"dist","build",".next","coverage","generated","__generated__","vendor"}
header_rx = re.compile(r"(generated file|do not edit|auto-generated|autogenerated)", re.I)
findings = []

for p in root.rglob("*"):
    if not p.is_file() or any(part in skip for part in p.parts):
        continue
    rel = p.relative_to(root)
    reasons = []
    if any(part in generated_dirs for part in rel.parts[:-1]):
        reasons.append("generated/output directory")
    if re.search(r"(?i)(\.generated\.|_generated\.|\.gen\.)", p.name):
        reasons.append("generated filename")
    if p.stat().st_size < 1_000_000:
        try:
            head = p.read_text(encoding="utf-8", errors="ignore")[:3000]
            if header_rx.search(head):
                reasons.append("generated header")
        except Exception:
            pass
    if reasons:
        findings.append({"file": str(rel), "reasons": reasons})
print(json.dumps({"generated_candidates": findings}, indent=2))
