// Static asset caching: assets must revalidate (ETag + no-cache) so a deploy
// that changes a CSS/JS file reaches returning users immediately instead of
// being masked by a long max-age cache.
//
// assets_bundled.js is generated by build.js (gitignored) and isn't present in
// CI's test step, so we mock it — this test only exercises the caching logic.

import { describe, it, expect } from "bun:test";

import { serveStaticAsset } from "../middleware/static-assets.js";

const testAssets = {
  "/assets/app.css": ["/* app.css */ .x{}", ".css"],
  "/assets/cookie-consent.css": [".yr-consent { position: fixed; }", ".css"],
  "/assets/dashboard.js": ["/* dashboard.js */ console.log(1)", ".js"],
};

const reqWith = (headers = {}) => new Request("https://test.com/assets/app.css", { headers });

describe("serveStaticAsset caching", () => {
  it("serves a known asset with a revalidating cache policy and an ETag", async () => {
    const res = serveStaticAsset("/assets/app.css", reqWith(), testAssets);
    expect(res.status).toBe(200);
    const cc = res.headers.get("cache-control") || "";
    expect(cc).toMatch(/no-cache/);
    expect(cc).not.toMatch(/max-age=\s*(?!0)\d/); // no long max-age
    expect(res.headers.get("etag")).toBeTruthy();
    expect(res.headers.get("content-type")).toMatch(/text\/css/);
  });

  it("serves the consent stylesheet as CSS", () => {
    const res = serveStaticAsset("/assets/cookie-consent.css", reqWith(), testAssets);
    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toBe("text/css; charset=utf-8");
    expect(res.headers.get("cache-control")).toContain("no-cache");
  });

  it("returns 304 when If-None-Match matches the current ETag", async () => {
    const first = serveStaticAsset("/assets/app.css", reqWith(), testAssets);
    const etag = first.headers.get("etag");
    const res = serveStaticAsset("/assets/app.css", reqWith({ "if-none-match": etag }), testAssets);
    expect(res.status).toBe(304);
  });

  it("returns full content (200) when If-None-Match is stale", async () => {
    const res = serveStaticAsset("/assets/app.css", reqWith({ "if-none-match": '"stale-etag"' }), testAssets);
    expect(res.status).toBe(200);
    expect((await res.text()).length).toBeGreaterThan(0);
  });

  it("gives different assets different ETags", () => {
    const a = serveStaticAsset("/assets/app.css", reqWith(), testAssets).headers.get("etag");
    const b = serveStaticAsset("/assets/dashboard.js", reqWith(), testAssets).headers.get("etag");
    expect(a).not.toBe(b);
  });

  it("404s an unknown asset", () => {
    expect(serveStaticAsset("/assets/nope.css", reqWith(), testAssets).status).toBe(404);
  });

  it("serves page scripts from the bundled asset map", () => {
    const assets = {
      ...testAssets,
      "/assets/invite.js": ["document.body.dataset.invite = 'ready';", ".js"],
      "/assets/dialog.js": ["window.yrDialog = {};", ".js"],
    };
    expect(serveStaticAsset("/assets/invite.js", new Request("https://test.com/assets/invite.js"), assets).status).toBe(200);
    expect(serveStaticAsset("/assets/dialog.js", new Request("https://test.com/assets/dialog.js"), assets).status).toBe(200);
  });

  it("serves WebP media with binary content and revalidatable caching", async () => {
    const assets = {
      ...testAssets,
      "/assets/leaderboards-640.webp": ["UklGRg==", ".webp", "base64"],
    };
    const res = serveStaticAsset("/assets/leaderboards-640.webp", new Request("https://test.com/assets/leaderboards-640.webp"), assets);
    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toBe("image/webp");
  expect(res.headers.get("cache-control")).toContain("max-age=604800");
    expect(new Uint8Array(await res.arrayBuffer())).toEqual(new Uint8Array([0x52, 0x49, 0x46, 0x46]));
  });
});
